const Index = () => {
    return (
        <div className="py-30 bg-black flex flex-col items-center justify-center">

            <div className="w-[60vw]">
                <h1 className="text-5xl text-red-500 text-center">Privacy Policy</h1>

                <p className="text-[14px]">Last Updated: October 15, 2025</p> <p className="text-[18px] font-bold">Introduction</p> <p className="text-[14px]">This Privacy Policy explains how TEDxVSSUT ("we", "our", "us") collects, uses, stores, and protects personal data in accordance with the General Data Protection Regulation (GDPR).</p> <p className="text-[18px] font-bold">Information We Collect</p> <p className="text-[14px]">We collect the following personal data when you purchase tickets or register on our website: name, email address, phone number, and college name or affiliation.</p> <p className="text-[18px] font-bold">Purpose of Data Collection</p> <p className="text-[14px]">We use personal data to process and confirm ticket purchases, send event-related information and updates, communicate future event announcements and promotions, and to improve our services and user experience.</p> <p className="text-[18px] font-bold">Legal Basis for Processing</p> <p className="text-[14px]">We process personal data on the following legal bases: contractual necessity to fulfill ticket purchases; legitimate interests to send updates and marketing about TEDxVSSUT events; and consent where required for marketing communications.</p> <p className="text-[18px] font-bold">Data Retention</p> <p className="text-[14px]">We retain personal data only as long as necessary to fulfill the purposes for which it was collected or as required by law. When data is no longer needed it will be securely deleted.</p> <p className="text-[18px] font-bold">Data Sharing</p> <p className="text-[14px]">We do not sell, rent, or share your personal data with third parties. Your information is used only by TEDxVSSUT for communication and event-related purposes.</p> <p className="text-[18px] font-bold">Data Security</p> <p className="text-[14px]">We implement appropriate technical and organizational measures to protect personal data against unauthorized access, disclosure, alteration, or destruction. Access to personal data is limited to authorized TEDxVSSUT team members.</p> <p className="text-[18px] font-bold">Your Rights Under GDPR</p> <p className="text-[14px]">You have the right to access and obtain a copy of your data; request correction of inaccurate or incomplete data; request deletion of your data; request restriction or object to processing in certain circumstances; and withdraw consent where processing is based on consent. To exercise these rights, contact us using the details below.</p> <p className="text-[18px] font-bold">Contact Information</p> <p className="text-[14px]">If you have questions about this Privacy Policy or wish to exercise your rights, contact us at: Email: help.tedxvssut@gmail.com Website: https://tedxvssut.in</p> <p className="text-[18px] font-bold">Policy Updates</p> <p className="text-[14px]">We may update this Privacy Policy from time to time. Any changes will be posted on this page with the updated date.</p>
            </div>
        </div>
    )
}
export default Index;